<#
    Setup-Kiosk.ps1  (toggle edition)
    ---------------------------------------------------------------
    Installs a single desktop icon that:
        tap  -> locks down Windows, opens the ONS map fullscreen
        Alt+F4 -> unlocks Windows, returns a normal usable desktop

    Nothing is left applied when the kiosk is not running, so the PC
    stays a normal machine between sessions. No reboot, no autostart.

    HOW IT WORKS
      A scheduled task ("ONS Kiosk Session") runs the session script
      elevated, so tapping the icon never shows a UAC prompt. The
      session script applies the lockdown, launches Edge, waits for
      Edge to exit, then reverts everything.

    RUN ONCE, AS ADMINISTRATOR:
      powershell -ExecutionPolicy Bypass -File .\Setup-Kiosk.ps1

    Two icons are created on the desktop:
      "ONS Map"          - start the kiosk
      "Restore Desktop"  - manual unlock, in case a session is
                           interrupted and the revert never ran
#>

[CmdletBinding()]
param(
    [string]$Url          = "https://sidagis.github.io/ONS/theMap.html",
    [string]$KioskDir     = "C:\Kiosk",
    [string]$TaskName     = "ONS Kiosk Session"
)

$ErrorActionPreference = "Stop"

if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "Run this as Administrator." -ForegroundColor Red; exit 1
}

function Write-Step { param($m) Write-Host "  [+] $m" -ForegroundColor Cyan }

Write-Host "`n=== ONS kiosk setup (toggle edition) ===" -ForegroundColor Green
Write-Host "URL: $Url`n"

$edge = @(
    "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
    "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe"
) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $edge) { throw "msedge.exe not found." }
Write-Step "Found Edge: $edge"

New-Item -Path $KioskDir -ItemType Directory -Force | Out-Null
$sessionScript = Join-Path $KioskDir "Kiosk-Session.ps1"
$configFile    = Join-Path $KioskDir "kiosk-url.txt"
Set-Content -Path $configFile -Value $Url -Encoding ASCII
Write-Step "Kiosk folder: $KioskDir  (URL stored in kiosk-url.txt)"

# =============================================================================
#  SESSION SCRIPT - applies lockdown, runs Edge, reverts on exit
# =============================================================================
$session = @'
<#  Kiosk-Session.ps1 - generated by Setup-Kiosk.ps1
    Runs elevated via scheduled task. Do not run directly.
    -Revert only undoes the lockdown (used by the Restore Desktop icon). #>
param([switch]$Revert)

$ErrorActionPreference = "SilentlyContinue"

$KioskDir   = "__KIOSKDIR__"
$Edge       = "__EDGE__"
$ProfileDir = Join-Path $KioskDir "profile"
$FlagFile   = Join-Path $KioskDir "session.active"
$LogFile    = Join-Path $KioskDir "session.log"

function Log { param($m) "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss')  $m" | Add-Content $LogFile }

# --- find the interactive user's registry hive -------------------------------
function Get-UserHive {
    $p = Get-CimInstance Win32_Process -Filter "Name='explorer.exe'" | Select-Object -First 1
    if ($p) {
        $sid = (Invoke-CimMethod -InputObject $p -MethodName GetOwnerSid).Sid
        if ($sid -and (Test-Path "Registry::HKEY_USERS\$sid")) { return "Registry::HKEY_USERS\$sid" }
    }
    return "Registry::HKEY_CURRENT_USER"
}
$UH = Get-UserHive

function Set-Reg {
    param($Path,$Name,$Value,[string]$Type="DWord")
    if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
    New-ItemProperty -Path $Path -Name $Name -Value $Value -PropertyType $Type -Force | Out-Null
}
function Del-Key { param($p) if (Test-Path $p) { Remove-Item $p -Recurse -Force } }
function Del-Val { param($p,$n) if (Test-Path $p) { Remove-ItemProperty $p -Name $n -Force } }

function Set-Taskbar-AutoHide {
    param([bool]$On)
    $sr = "$UH\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3"
    if (-not (Test-Path $sr)) { return }
    $b = (Get-ItemProperty -Path $sr -Name Settings).Settings
    if ($On) { $b[8] = $b[8] -bor 0x01 } else { $b[8] = $b[8] -band 0xFE }
    Set-ItemProperty -Path $sr -Name Settings -Value $b -Force
}

function Restart-Explorer {
    Stop-Process -Name explorer -Force
    Start-Sleep -Seconds 2   # Windows relaunches it automatically
}

# =============================== LOCK DOWN ===================================
function Enable-Lockdown {
    Log "applying lockdown"

    # --- Edge policy: allowlist the map's hosts, block all else -------------
    $E = "HKLM:\SOFTWARE\Policies\Microsoft\Edge"
    $allow = @(
        "sidagis.github.io"
        "*.githubusercontent.com"
        "*.arcgis.com"
        "*.arcgisonline.com"
        "*.sodir.no"
    )
    Del-Key "$E\URLAllowlist"; Del-Key "$E\URLBlocklist"
    for ($i=0; $i -lt $allow.Count; $i++) { Set-Reg "$E\URLAllowlist" ($i+1) $allow[$i] "String" }
    Set-Reg "$E\URLBlocklist" "1" "*" "String"

    Set-Reg $E "DeveloperToolsAvailability"  2
    Set-Reg $E "PrintingEnabled"             0
    Set-Reg $E "TranslateEnabled"            0
    Set-Reg $E "BrowserSignin"               0
    Set-Reg $E "PasswordManagerEnabled"      0
    Set-Reg $E "DefaultNotificationsSetting" 2
    Set-Reg $E "DefaultGeolocationSetting"   2
    Set-Reg $E "DefaultPopupsSetting"        2
    Set-Reg $E "AllowSurfGame"               0
    Set-Reg $E "HideFirstRunExperience"      1
    Set-Reg $E "DownloadRestrictions"        3
    Set-Reg $E "InPrivateModeAvailability"   1
    Set-Reg $E "EdgeCollectionsEnabled"      0
    Set-Reg $E "ShowRecommendationsEnabled"  0
    Set-Reg $E "PromotionalTabsEnabled"      0
    Set-Reg $E "UserFeedbackAllowed"         0

    # --- shell touch gestures ------------------------------------------------
    Set-Reg "HKLM:\SOFTWARE\Policies\Microsoft\Windows\EdgeUI" "AllowEdgeSwipe"   0
    Set-Reg "HKLM:\SOFTWARE\Policies\Microsoft\Windows\EdgeUI" "TurnOffBackstack" 1
    Set-Reg "HKLM:\SOFTWARE\Policies\Microsoft\Dsh" "AllowNewsAndInterests" 0
    Set-Reg "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot" "TurnOffWindowsCopilot" 1

    # --- notifications -------------------------------------------------------
    Set-Reg "$UH\SOFTWARE\Policies\Microsoft\Windows\Explorer" "DisableNotificationCenter" 1
    Set-Reg "$UH\Software\Microsoft\Windows\CurrentVersion\PushNotifications" "ToastEnabled" 0

    # --- taskbar -------------------------------------------------------------
    $adv = "$UH\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
    Set-Reg $adv "ShowTaskViewButton" 0
    Set-Reg $adv "TaskbarDa"          0
    Set-Reg $adv "TaskbarMn"          0
    Set-Taskbar-AutoHide $true

    # --- touch keyboard ------------------------------------------------------
    Set-Service -Name TabletInputService -StartupType Disabled
    Stop-Service -Name TabletInputService -Force

    # --- no sleep / no screensaver / no auto-lock ----------------------------
    powercfg /change monitor-timeout-ac 0  | Out-Null
    powercfg /change standby-timeout-ac 0  | Out-Null
    Set-Reg "$UH\Control Panel\Desktop" "ScreenSaveActive" "0" "String"
    Set-Reg "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "InactivityTimeoutSecs" 0

    New-Item -Path $FlagFile -ItemType File -Force | Out-Null
    Restart-Explorer
    Log "lockdown applied"
}

# ================================ RELEASE ====================================
function Disable-Lockdown {
    Log "reverting lockdown"

    Del-Key "HKLM:\SOFTWARE\Policies\Microsoft\Edge"
    Del-Key "HKLM:\SOFTWARE\Policies\Microsoft\Windows\EdgeUI"
    Del-Key "HKLM:\SOFTWARE\Policies\Microsoft\Dsh"
    Del-Key "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot"

    Del-Val "$UH\SOFTWARE\Policies\Microsoft\Windows\Explorer" "DisableNotificationCenter"
    Set-Reg "$UH\Software\Microsoft\Windows\CurrentVersion\PushNotifications" "ToastEnabled" 1

    $adv = "$UH\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
    Set-Reg $adv "ShowTaskViewButton" 1
    Set-Reg $adv "TaskbarDa"          1
    Set-Taskbar-AutoHide $false

    Set-Service -Name TabletInputService -StartupType Manual
    Start-Service -Name TabletInputService

    powercfg /change monitor-timeout-ac 15 | Out-Null
    powercfg /change standby-timeout-ac 30 | Out-Null
    Set-Reg "$UH\Control Panel\Desktop" "ScreenSaveActive" "1" "String"
    Del-Val "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "InactivityTimeoutSecs"

    Remove-Item $FlagFile -Force
    Restart-Explorer
    Log "desktop restored"
}

# ================================== MAIN =====================================
if ($Revert) { Disable-Lockdown; return }

try {
    Get-Process msedge | Stop-Process -Force
    Start-Sleep -Milliseconds 800

    Enable-Lockdown

    # throwaway profile => always a fresh pull from GitHub Pages
    Remove-Item $ProfileDir -Recurse -Force
    Start-Sleep -Milliseconds 300

    $url = (Get-Content (Join-Path $KioskDir "kiosk-url.txt") -Raw).Trim()
    $bust = "v=" + [DateTimeOffset]::Now.ToUnixTimeSeconds()
    $url += $(if ($url -match "\?") { "&$bust" } else { "?$bust" })

    $args = @(
        "--kiosk", $url
        "--edge-kiosk-type=fullscreen"
        "--kiosk-idle-timeout-minutes=0"
        "--user-data-dir=$ProfileDir"
        "--no-first-run"
        "--no-default-browser-check"
        "--disable-pinch"
        "--overscroll-history-navigation=0"
        "--noerrdialogs"
        "--disable-infobars"
        "--hide-crash-restore-bubble"
        "--disable-session-crashed-bubble"
        "--disable-background-networking"
        "--disable-component-update"
        "--disable-features=msEdgeSplitScreen,msWebOOUI,msPdfOOUI"
    )
    Log "launching Edge"
    Start-Process -FilePath $Edge -ArgumentList $args

    # wait for the last Edge process to disappear (Alt+F4 on the stand)
    Start-Sleep -Seconds 5
    while (Get-Process msedge -ErrorAction SilentlyContinue) { Start-Sleep -Seconds 2 }
    Log "Edge exited"
}
catch { Log "ERROR: $($_.Exception.Message)" }
finally { Disable-Lockdown }
'@

$session = $session.Replace("__KIOSKDIR__", $KioskDir).Replace("__EDGE__", $edge)
Set-Content -Path $sessionScript -Value $session -Encoding UTF8
Write-Step "Wrote session script: $sessionScript"

# =============================================================================
#  SCHEDULED TASK - lets the icon run elevated with no UAC prompt
# =============================================================================
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action = New-ScheduledTaskAction -Execute "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$sessionScript`""
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew
Register-ScheduledTask -TaskName $TaskName -Action $action -Principal $principal -Settings $settings | Out-Null
Write-Step "Registered scheduled task '$TaskName' (runs as SYSTEM, no UAC prompt)"

# Same task, revert mode, for the Restore Desktop icon
$revertTask = "$TaskName Revert"
Unregister-ScheduledTask -TaskName $revertTask -Confirm:$false -ErrorAction SilentlyContinue
$actionR = New-ScheduledTaskAction -Execute "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$sessionScript`" -Revert"
Register-ScheduledTask -TaskName $revertTask -Action $actionR -Principal $principal -Settings $settings | Out-Null
Write-Step "Registered revert task"

# =============================================================================
#  DESKTOP ICONS
# =============================================================================
$wsh = New-Object -ComObject WScript.Shell
$desk = Join-Path $env:PUBLIC "Desktop"

function New-Lnk {
    param($Name,$TaskToRun,$Icon,$Desc)
    $p = Join-Path $desk "$Name.lnk"
    $s = $wsh.CreateShortcut($p)
    $s.TargetPath       = "$env:SystemRoot\System32\schtasks.exe"
    $s.Arguments        = "/run /tn `"$TaskToRun`""
    $s.WorkingDirectory = $KioskDir
    $s.IconLocation     = $Icon
    $s.Description      = $Desc
    $s.WindowStyle      = 7
    $s.Save()
    return $p
}

New-Lnk "ONS Map"         $TaskName   "$edge,0"                              "Start the ONS map kiosk" | Out-Null
New-Lnk "Restore Desktop" $revertTask "$env:SystemRoot\System32\shell32.dll,220" "Unlock Windows if a kiosk session was interrupted" | Out-Null
Write-Step "Desktop icons created: 'ONS Map', 'Restore Desktop'"

Write-Host "`nDone - no reboot needed.`n" -ForegroundColor Green
Write-Host "TEST NOW" -ForegroundColor Yellow
Write-Host "  1. Tap 'ONS Map'. The screen will flicker once (Explorer restart), then the map opens fullscreen."
Write-Host "  2. Check every button's layers draw, including basemap tiles and the wind layer."
Write-Host "  3. Press Alt+F4. The desktop should come back fully usable - taskbar visible,"
Write-Host "     touch keyboard working, Edge able to browse normally again."
Write-Host "  4. If a session ever gets interrupted, tap 'Restore Desktop'."
Write-Host "`n  Log: $KioskDir\session.log`n"
